### ISSUE TITLE
source.zip grows forever

### ISSUE THREAD

**Issue by jaymefosa** [White-Link/gpm#1]
Running on celebA, source.zip will grow until the experiment is killed

**Comment by White-Link** [comment]
Hi, sorry for the late answer and thanks for your interest in our work!
This is probably because you are choosing the log folder (`$LOG_PATH` in our README) in the root folder of the project, as, by design, the code zips the whole root folder to archive the whole source code (cf. [the warning at the end of this section](https://github.com/White-Link/gpm#launch-an-experiment)).
Could you confirm that this is the case and that choosing another log folder solves the issue?

**Comment by jaymefosa** [comment]
Yes that was it, thank you! After moving the log directory completely outside of the repo there was no issue. I misunderstood 'code folder' meant the internal gpm directory.
