### ISSUE TITLE
Cifar10 configuration

### ISSUE THREAD

**Issue by SYZhang0805** [White-Link/gpm#2]
If I want to do the experiment on Cifar10 dataset, how do I set the configuration?

**Comment by White-Link** [comment]
Hi, thanks for your interest in our work!

We do not currently support CIFAR-10 in our code, since we did not perform experiments in our paper on this dataset. However, if you would like to integrate it yourself, its implementation should be very similar to the one of MNIST, given their similarity in PyTorch. For this, you can follow our implementation of the MNIST dataset throughout the folder `gpm/data`.

Do not hesitate to let us know whether you have any other question.
